apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: k8s-dashboard-auth
  labels:
    app: k8s-dashboard-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
  namespace: k8s-dashboard-auth
  labels:
    app: k8s-dashboard-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: k8s-dashboard-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-secret
  namespace: k8s-dashboard-auth
  labels:
    app: k8s-dashboard-auth
  annotations:
    kubernetes.io/service-account.name: "admin-user"
type: kubernetes.io/service-account-token
